// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlrjJyJ-POSmP0nM9AZMb8LabdTlDywM',
    appId: '1:1064205569459:web:6ed166575cf53063374fc6',
    messagingSenderId: '1064205569459',
    projectId: 'ekhaya-live',
    authDomain: 'ekhaya-live.firebaseapp.com',
    storageBucket: 'ekhaya-live.firebasestorage.app',
    measurementId: 'G-Z5F2EVETC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8RnIqoVs3HIZiB1uOi7dUM6nufmqmiY',
    appId: '1:1064205569459:android:c368bb7f19e5f8bc374fc6',
    messagingSenderId: '1064205569459',
    projectId: 'ekhaya-live',
    storageBucket: 'ekhaya-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSwOCwuufcDY7pxSkbvyVcAKLu6_BW_c',
    appId: '1:1064205569459:ios:f42eff2a7acc59be374fc6',
    messagingSenderId: '1064205569459',
    projectId: 'ekhaya-live',
    storageBucket: 'ekhaya-live.firebasestorage.app',
    iosClientId: '1064205569459-v6m343bdnduau5kuqeolh94bul893t6t.apps.googleusercontent.com',
    iosBundleId: 'com.matchmalawi.matchmalawi',
  );
}
